### PR TITLE
Fixes issue with resetting redis job keys on startup

### PR DESCRIPTION
**Pull request by chenkirk**
This addresses https://github.com/flippa/allora/issues/2

### CODE REVIEW

**Comment by d11wtq** [comment]
Good catch, thanks!

**Comment by d11wtq** [comment]
Ah, I can't merge this for you, as I no longer work at Flippa. Will have to wait for somebody else @ags? :)

**Comment by ags** [comment]
:+1: Thanks @chenkirk and @d11wtq :)

**Comment by ags** [comment]
[CHANGELOG updated](https://github.com/flippa/allora/blob/master/CHANGELOG.md) and 0.1.8 pushed to [rubygems](https://rubygems.org/gems/allora).

**Pull request merged**
